Feature/mypage : get 메소드 개발 완
wecode-bootcamp-korea/49-3rd-DKDK-backend pull request #12
Opened 2023-10-18 14:39 UTC by kroonstazy

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?

DKDK (득근득근) mypage는 다양한 정보를 표출 합니다.
가입 시 유저가 입력한 키, 체중, 관심운동(헬스, 필라테스, 요가 등)에 기반하여, 개인의 칼로리에 맞는 식단, 관심운동 추천을 제공하고 있습니다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

유저는 본인에게 필요한 정보를 하나의 페이지에서 확인 할 수 있습니다, 다양하게 제공되는 식단과 운동 추천도 받을 수 있습니다.

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

추가로 본 제품의 유료 구독 서비스 구매여부, 구독 만료일을 확인 할 수 있고, 유저가 트레이너 PT를 구매하였을때,
트레이너 정보, 트레이너의 고객 수, 트레이너가 얼마나 활발하게 피드백을 남기는지 또한 한페이지에서 확인 할 수 있습니다.

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />
<a href="https://documenter.getpostman.com/view/29425001/2s9YR9XCHP">myPage : GET API</a>
<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- 서브쿼리를 사용 할 수 있게 되었습니다.
- 이전부터  "SQL 연습을 많이 해야 겠다, 하고싶다." 라는 생각만 있었는데 이번 제품을 개발하면서, 다양한 테이블의 값을 JOIN 문, 서브쿼리를 사용하여 원하는 값을 필터링하는 법을 배웠습니다.
- COUNT, DISTINCT, DATE(), DATE_ADD() : 등을 사용하여 원하는 값을 count하고, distinct를 사용하여, unique한 값을 조회, DATE_ADD(created_at, INTERVAL term MONTH) 사용하여, 새로운 column에 원하는 date을 넣을 수 있게 되었습니다.

- throw / throwError에 대해 확실히 이해 할 수 있게 되었습니다.
- supertest를 사용하여 unittest를 진행 할 수 있게 되었습니다.

2023-10-18 16:07 UTC, soheon-lee requested changes
테스트 완료하시면 알려주세요 :)

2023-10-18 16:07 UTC, soheon-lee commented on src/services/mypageService.js
> +  };
1. userInfo라는 변수가 없는 것 같은데, 여기 API 동작할 수 있나요?
2. 테스트케이스에서 또한 해당 property를 찾을 수 없다고 나오는 것 같습니다.

<img width="826" alt="image" src="https://github.com/wecode-bootcamp-korea/49-3rd-DKDK-backend/assets/42701133/3238f297-f1b6-4cc3-bb3a-b9730c36a3ce">

혹시 제가 놓친게 있다면 확인 부탁드립니다 :)

2023-10-18 16:07 UTC, soheon-lee commented on src/routes/index.js
> +
```suggestion
const userHealthInfoRouter = require("./userHealthInfoRouter");

const routes = express.Router();
// try-catch문에 대해서 err catch 해주는 부분이 라우터 단에서 필요하다.

routes.use("/userHealthInfo", userHealthInfoRouter);

```
- router, controller, service, models는 우리가 주로 다루는 데이터(자원, resource, entity)단위로 구분해 주시는 것이 좋습니다.
- Entity 가운데 mypage라는 것은 없고, 사실상 유저 정보라서, user와 관련된 네이밍을 추천드립니다.
- `users` Entity 관련 데이터라고 하기엔 행정적인 사용자 정보가 아닌, 서비스적인 사용자 정보를 다루는 API로 보이네요. 많이 고민하다가 userHealthInfo 라는 Entity 명을 추천드립니다. 변경하셔도 좋습니다 :)

2023-10-19 03:43 UTC, kroonstazy commented on src/services/mypageService.js
> +  };
안녕하세요 소헌님, 늦은시간 리뷰 남겨주셔서 감사합니다!

1. 어제 PR을 보낸후 테스트를 더 진행한 결과 users 테이블에 전달하는 id가 없을때 해당에러가 발생하는것을 확인 했습니다.
2. 일반적으로 로그인 이후에 발급되는 Token에서 userId를 추출하여 사용할 것을 상정하여 작성했습니다.
3. 하지만 분기처리 및 throwError 연습을 위해서, db에서 userId 조회 후 userId가 조회 되지 않을때 에러 response를 보내는것으로 분기처리 해보겠습니다.

P.S - 로그인/회원가입 부분이 완료되면 토큰확인하는 미들웨어를 사용하여 코드 수정에 들어갈 예정입니다.

코드 수정 후 다시 한번 리뷰요청 태그 걸도록 하겠습니다.

감사합니다.

2023-10-19 04:13 UTC, kroonstazy commented on src/routes/index.js
> +
소헌님 질문이 있습니다. 이렇게 라우터 명을 변경하는 경우에는. 그동안 mypageRouter, mypageController, mypageService, mypageDao를 모두 
userHealthInfo____으로 변경해야 하나요?

2023-10-19 04:15 UTC, soheon-lee commented on src/routes/index.js
> +
@kroonstazy 네 그렇습니다! :) 한세트로 변경해주시면 됩니다!

2023-10-19 05:11 UTC, soheon-lee commented
@kroonstazy 
INFO_LOAD 하는 테스트케이스에서 문제가 있는 것 같습니다.

1. 사용자 정보를 가져오는 테스트케이스가 정상동작하려면, 테스트 함수 실행 전, 사용자 정보를 테스트 DB에 미리 1개 넣어두는 사전 작업이 필요합니다.
2. beforeAll() 메소드에서 유저 정보를 미리 입력해 주세요.

<img width="1059" alt="image" src="https://github.com/wecode-bootcamp-korea/49-3rd-DKDK-backend/assets/42701133/9282a2d5-468d-4214-9e13-53cc07fadfef">

2023-10-19 05:20 UTC, soheon-lee commented
(추가 리뷰중)

2023-10-19 05:20 UTC, soheon-lee commented on .env.test
1. `.env.test` 파일도 git에 올라오면 안됩니다.
2. `env.test.sample` 파일로 대체해서 올려주시면 되겠습니다.
3. git에 이미 한 번 올라온 파일은 삭제하는 것이 아니라 git 명령어를 통해 잘못 올라온 파일을 내려주셔야 합니다 :)

2023-10-19 05:20 UTC, soheon-lee commented on src/controllers/userHealthInfoController.js
> +
사용되지 않는 코드는 백업하신 후, 제거해주세요 :)

2023-10-19 05:20 UTC, soheon-lee commented on src/models/userHealthInfoDao.js
> +
```suggestion

const checkExistence = async (userId) => {
  const exist = await AppDataSource.query(
  ` SELECT id FROM users where id = ?`,
  [userId]
  );
  return exist.length === 1;
  };

```
사용자는 1명 뿐이어야 하니, length 가 1 인지 여부를 곧바로 전달 하면, 불필요한 3항 연산자를 줄일 수 있을 것 같습니다 :)

2023-10-19 05:54 UTC, kroonstazy commented on src/models/userHealthInfoDao.js
> +
와 그렇네요!
어차피 `exist.length === 1`  조건에서 true/false 값이 전달이 되네요
크으! 이마를 탁 칩니다!

2023-10-19 05:56 UTC, kroonstazy commented on src/controllers/userHealthInfoController.js
> +
넵 앞으로 주의 하겠습니다.

2023-10-19 06:24 UTC, kroonstazy commented on .env.test
1. `git rm -r --cached .env.test` 사용하여 파일 내림
2. env.test.sample 생성하였습니다.

2023-10-19 06:25 UTC, kroonstazy commented on src/controllers/userHealthInfoController.js
> +
하단의 리뷰반영 커밋에 사용하지 않는 코드 백업 후, 삭제하여 다시 커밋하였습니다.

2023-10-19 06:25 UTC, kroonstazy commented on src/models/userHealthInfoDao.js
> +
리뷰반영 커밋에 적용하였습니다.

2023-10-19 06:46 UTC, soheon-lee requested changes, later dismissed

2023-10-19 06:46 UTC, soheon-lee commented on src/models/userHealthInfoDao.js
> +
2개 이상의 테이블의 데이터가 동시에 변경되기 때문에, 중간에 에러가 났을 때 한 쪽 테이블만 변경된 상태가 되지 않도록 transaction 처리가 필요합니다 :)

2023-10-19 06:46 UTC, soheon-lee commented on src/models/userHealthInfoDao.js
> +      (SELECT u.img_url FROM users u WHERE u.id = t.user_id) AS profileImg,
같은 테이블에 subquery를 2개 생성하는데, 혹시 한 번에 select해서 aliasing까지 할 수 있는지 한 번 알아봐주세요 :)

2023-10-19 06:46 UTC, soheon-lee commented on src/models/userHealthInfoDao.js
> +      (SELECT u.img_url FROM users u WHERE u.id = t.user_id) AS profileImg,
지금 상황에서 꼭 필요한 join과 sub query이긴 한 것 같은데, 조금 더 고민이 필요하겠네요! 기능상 수정하셔야 할 건 없는데, 아래 블로그 한 번 읽어보시면 좋겠습니다!

https://schatz37.tistory.com/3

2023-10-19 06:46 UTC, soheon-lee commented on src/models/userHealthInfoDao.js
> +  trainerUpdate,
1. 이 가운데 아직 쓰이지 않는 함수가 있는거 같네요, ex. trainerUpdate, checkTrainer 등.
2. 아직 사용되고 있지 않는 함수들은 다른 브랜치에 백업해주시고, 해당 PR에서는 코드 제거해 주세요 :)

2023-10-19 07:44 UTC, kroonstazy commented on src/models/userHealthInfoDao.js
> +      (SELECT u.img_url FROM users u WHERE u.id = t.user_id) AS profileImg,
> 같은 테이블에 subquery를 2개 생성하는데, 혹시 한 번에 select해서 aliasing까지 할 수 있는지 한 번 알아봐주세요 :)

안그래도 같은 users 테이블에서, 트레이너의 닉네임, 프로파일 이미지를 위해서, 같은 내용의 서브쿼리를 2번 작성하는데에 고민이 많았습니다. 최적화 시도도 많이 해봤는데 한번에 다양한 정보를 한번에 얻으려고 하다보니까 쿼리문이 너무 복잡해졌습니다.

보내주신 블로그 글에서 데이터가 적을때는 상관없지만  데이터가 많아지면 서브쿼리와 JOIN 문을 많이 연산속도가 느려진다는것을 읽었습니다. 
> 각각, 필요한 정보를 추출하는 DAO를 만들어서 Service 에서 Array, Object로 만들어서 보내주는 방법도 고려해 보았지만 이번에는 SQL문을 좀 깊게 파보고 싶었습니다. 
어떻게 진행하는게 더 효율적인 방법인지 궁금합니다.

P.S. - 이 부분은 수정은 안해도 되는게 맞는건가요?

2023-10-19 07:46 UTC, soheon-lee commented on src/models/userHealthInfoDao.js
> +      (SELECT u.img_url FROM users u WHERE u.id = t.user_id) AS profileImg,
@kroonstazy 
아 네 수정 안해도 괜찮을 것 같습니다.
일반적으로는 javascript의 연산 속도 (배열 연산) 보다는 SQL의 쿼리 속도가 빠른 편입니다!

2023-10-19 07:55 UTC, kroonstazy commented on src/models/userHealthInfoDao.js
> +
해당 내용은 새로운 feature/mypagebackup에서 transaction () 적용하도록 하겠습니다.
GET - Method에 해당하는 내용이 아니라 현재 PR에는 삭제 하였습니다.

2023-10-19 07:58 UTC, kroonstazy commented on src/models/userHealthInfoDao.js
> +  trainerUpdate,
안녕하세요 소헌님~
사용하지 않는 코드라고 말씀 하셨을때, 태그아웃 시킨 코드만 말씀하시는줄 알았는데 기능적 / entity 측면에서 말씀하신거였군요!

checkTrainer, userUpdate, trainerUpdate는 마이페이지 내에서 유저 정보를 수정하는 기능은 현재 브랜치에서 삭제하였습니다.

말씀하신대로 새로운 브랜치를 만들어서 백업해 놨습니다.

2023-10-19 08:54 UTC, kroonstazy commented
소헌님이 보여주신대로,
0. 이전에 생성된 test db가 있다면 날린다.
1. dbmate up으로 눈보다 더 희고 깨끗한 db를 생성한다.
2. npm test를 실행한다.
3. <img width="286" alt="Screenshot 2023-10-19 at 17 54 06" src="https://github.com/wecode-bootcamp-korea/49-3rd-DKDK-backend/assets/70473564/34522a32-c5e4-4808-bd91-df879710c5db">

4. 제발 되라고 기도한다...

2023-10-19 09:02 UTC, soheon-lee reviewed
마지막 리뷰가 될 듯 싶습니다 동훈님... 화이팅!!

2023-10-19 09:02 UTC, soheon-lee commented on tests/userHealthInfo.test.js
> +    expect(res.body).toHaveProperty('data')
response body가 toHaveProperty가 아닌 응답 형태 그대로 테스트 하셔야 합니다. 프론트에게 전달되는 reponse의 형태가 잘 추출되는지 확인하기 위함입니다 :) res.body.expect()로 객체 형태 전부 검증해주세요 :)

2023-10-19 09:05 UTC, kroonstazy commented on tests/userHealthInfo.test.js
> +    expect(res.body).toHaveProperty('data')
왜 깃허브엔 😢 를 못달죠?
강해져서 돌아오겠습니다...

2023-10-19 11:30 UTC, kroonstazy commented on tests/userHealthInfo.test.js
> +    expect(res.body).toHaveProperty('data')
소헌님!!! 저 조금 강해진거 같아요!!!!!
객체형태 전부 검증했습니다!!

2023-10-19 13:04 UTC, soheon-lee requested changes
👼

2023-10-19 13:04 UTC, soheon-lee commented on src/models/userHealthInfoDao.js
> +};
```suggestion
const workoutRcmd = async (userId, limit = 5) => {
  return await AppDataSource.query(
    `
    SELECT * FROM workouts w
    JOIN workout_categories wc ON wc.id = w.category_id
    WHERE w.category_id = (SELECT interested_workout FROM users u WHERE u.id = ?)
    ORDER BY RAND()
    LIMIT ?;
    `,
    [userId, limit]
  );
};
```

2023-10-19 13:04 UTC, soheon-lee commented on src/services/userHealthInfoService.js
> +  const workoutRcmd = await userHealthInfoDao.workoutRcmd(userId);
```suggestion
  const workoutRcmd = await userHealthInfoDao.workoutRcmd(userId, workoutRcmdLimit);
```

2023-10-19 13:04 UTC, soheon-lee commented on src/services/userHealthInfoService.js
> +const getUserInfo = async (userId) => {
```suggestion
const getUserInfo = async (userId, workoutRcmdLimit) => {
```

2023-10-19 13:04 UTC, soheon-lee commented on src/controllers/userHealthInfoController.js
> +      data: await userHealthInfoService.getUserInfo(userId),
```suggestion
      data: await userHealthInfoService.getUserInfo(userId, workoutRcmdLimit),
```

2023-10-19 13:04 UTC, soheon-lee commented on src/controllers/userHealthInfoController.js
> +    const { userId } = req.query;
```suggestion
    const { userId, workoutRcmdLimit } = req.query;
```

2023-10-19 13:04 UTC, soheon-lee commented on src/models/userHealthInfoDao.js
> +const workoutRcmd = async (userId) => {
```suggestion
const getRandomWorkoutByUserId = async (userId) => {
```

2023-10-19 13:04 UTC, soheon-lee commented on src/models/userHealthInfoDao.js
> +const foodRcmd = async (grade) => {
```suggestion
const getRandomFoodByGrade = async (grade) => {
```

2023-10-19 13:04 UTC, soheon-lee commented on src/models/userHealthInfoDao.js
> +const subOrderInfo = async (userId) => {
```suggestion
const getSubOrdersInfoByUserId = async (userId) => {
```

2023-10-19 13:04 UTC, soheon-lee commented on src/models/userHealthInfoDao.js
> +const ptOrderInfo = async (userId) => {
```suggestion
const getPtOrderByUserId = async (userId) => {
```

2023-10-19 13:04 UTC, soheon-lee commented on src/models/userHealthInfoDao.js
> +const trainerInfo = async (userId) => {
```suggestion
const getTrainerInfo = async (userId) => {
```

2023-10-19 13:04 UTC, soheon-lee commented on src/models/userHealthInfoDao.js
> +const userInfo = async (userId) => {
```suggestion
const getUser = async (userId) => {
```

2023-10-19 14:03 UTC, soheon-lee approved these changes
드디어~! 수고 많으셨습니다 :)
Level up-!

LGTM!

2023-10-19 14:03 UTC, merged