Feature/trainermatching
wecode-bootcamp-korea/49-3rd-DKDK-backend pull request #17
Opened 2023-10-19 17:06 UTC by Wanderer94

## 1. 본 PR이 우리 팀의 웹 서비스 제품성에 어떠한 기여를 하였고, <br> 사용자에게 어떠한 기대효과를 전달하는지 작성해주세요.

- 내 PR이 제품 내 어떠한 기능적인 배경/전후맥락 가운데 개발되었나요?

  트레이너의 피드백을 받은 유저들은 자신과 잘 맞는 트레이너와의 오프라인 pt를 구매하고 싶을 것입니다. 트레이너의 정보를 좀 더 상세히 알아볼 수 있고 구매까지 가능한 기능을 구현하고자 했습니다.
 구독자가 아니고 회원이 아니더라도 트레이너들이 올린 pr글들은 확인해볼 수 있습니다. 이를 통해서 구독자의 수를 증대 시키고 매칭수수료를 통한 이익 증대를 노려볼 수 있습니다.

- 내 PR이 Merge 됨으로써 유저에게 전달되는 편익/기대효과는 무엇일까요?

  유저들이 가입하고 싶어하는 사이트로 느낄 수 있습니다. 자신과 잘 맞는 트레이너, 유명한 트레이너 등 유저가 원하는 조건의 트레이너와 매칭이 가능해 집니다.

<br />

## 2. 이 브랜치에서 어떤 내용을 개발했는지 큰 제목과 상세 내역을 적어주세요.

트레이너 글 목록
- 전체 글 목록 보여주기

트레이너 글 정렬 및 조건
- 유저가 원하는 조건으로 글을 정렬하는 기능

트레이너 상세글 (구현중)

트레이너 글 작성 (구현중)

트레이너 글 삭제 (구현중)
- 트레이너가 직접 글을 삭제 or 트레이너가 올린 글에 해당하는 pt권이 판매되었을 때 삭제

<br />

## 3. 개발한 화면을 캡쳐해서 첨부 해 주세요. 
<br />

- (drag & drop 또는 첨부파일 추가)

<br />

## 4. 이 브랜치에서 개발하면서 느꼇던 개발 성장포인트를 적어주세요.

- 쿼리빌더를 이용해 케이스를 나누어서 조건에 맞는 글을 보여 줄 수 있습니다.
  <br />

2023-10-20 03:25 UTC, soheon-lee reviewed
아직 기능 구현 중이신걸까요?
기능 더 구체화되기 전에 아래 코멘트 두개 한 번 확인해주세요!

2023-10-20 03:25 UTC, soheon-lee commented on src/services/trainerMatchingService.js
> +};
```suggestion
const getTrainerProduct = async (userId, offset, limit) => {
  //트레이너 확인 후 토큰 확인해서 구독 여부
  const isTrainer = trainerMatchingDao.isTrainer(userId);
  const isSubscribed = trainerMatchingDao.isSubscribed(userId);
  const isSub = true;
  if (isTrainer || isSubscript) {
    isSub = false;
  }
  const data = await trainerMatchingDao.getTrainerMatching(offset, limit);
  return { isSubscribed: isSub, data: data };
};
```
- 구독 여부라면 subscribed 단어가 보다 적절해 보입니다.
- `if (isTrainer || isSubscript)` 조건이 다소 헷갈리는데, 트레이너이거나 subscription이 이미 있으면, isSub를 거짓으로 하는 로직이 맞나요?

2023-10-20 03:25 UTC, soheon-lee commented on src/controllers/trainerMatchingController.js
> +    userId,
이 두경우를 분기처리 하지 않고, 하나의 service 내에서, builder로 처리하시는 것이 좋을 것 같습니다. 꼭 나눠야 하는 경우가 아닌 것 같은데, 제가 서비스 로직상 놓치고 있는게 있으면 알려주세요!

2023-10-20 05:03 UTC, Wanderer94 commented on src/services/trainerMatchingService.js
> +};
네네 맞습니다 subscribed로 바꿀게요 감사합니다!

2023-10-20 05:04 UTC, Wanderer94 commented on src/controllers/trainerMatchingController.js
> +    userId,
아 이해했습니다 빌더 구현 중이었어서 우선 저렇게 나누었는데 완성되는 대로 삭제하겠습니다 감사합니다!

2023-10-21 01:20 UTC, Wanderer94 commented
> 아직 기능 구현 중이신걸까요?
> 
> 기능 더 구체화되기 전에 아래 코멘트 두개 한 번 확인해주세요! 

확인했습니다!지금 해당 부분은 바꿔서 올렸습니다 delete까지 거의 구현했습니다

2023-10-23 09:11 UTC, soheon-lee requested changes
수고하셨습니다-!

2023-10-23 09:11 UTC, soheon-lee commented on src/routes/trainerMatchingRoute.js
> +  asyncWrap(trainerMatchingController.postTrainerProduct)
```suggestion
  asyncWrap(trainerMatchingController.createTrainerProduct)
```

2023-10-23 09:11 UTC, soheon-lee commented on src/services/trainerMatchingService.js
> +    isAuth = false;
저 이 로직이 아직 이해가 잘 안됐는데, 트레이너이면서 동시에 구독을 한 상태면, isAuth가 false가 되는걸까요?

즉 isTrainer === true && isSubsribed === true이면 어떻게 되나요?

2023-10-23 09:11 UTC, soheon-lee commented on src/models/trainerMatchingDao.js
> +const getTrainerMatchingDetail = async (userId, productsId) => {
```suggestion
const getTrainerMatchingDetail = async (userId, productId) => {
```

2023-10-23 09:11 UTC, soheon-lee commented on src/models/trainerMatchingDao.js
> +};
이 함수는 쓰이는 곳이 없는 것 같은데, 필요한 함수일까요?

2023-10-23 09:11 UTC, soheon-lee commented on src/models/trainerMatchingDao.js
> +  return category.name;
```suggestion
const findSpecializedCategoryByTrainerId = async (trainerId) => {
  const [category] = await AppDataSource.query(
    `
    SELECT wc.category AS name
    FROM workout_category wc
    JOIN trainers t ON t.specialized = wc.id
    WHERE t.id = ?;`,
    [trainerId]
  );
  return category.name;
```
어떤 아이디를 통해서 조회하는지가 명시되어 있지 않으면, 해당 함수를 사용하는 곳에서, 응당 categoryId로 오인하고 입력할 가능성이 있습니다. 확인부탁드립니다 :)

2023-10-23 09:11 UTC, soheon-lee commented on src/models/trainerMatchingDao.js
> +const postTrainerMatching = async (
```suggestion
const createTrainerMatching = async (
```

1. POST는 데이터를 입력한다는 의미가 있지만, 이는 HTTP method의 경우에 적용되는 명명 규칙이어서, Dao layer에서 사용하실 경우 create, get(find), update, delete 가운데 함수 이름을 선정하시는 편이 좋습니다.
2. 해당 함수는 두 개 이상의 테이블에 변동을 일으키는 작업을 포함하고 있기 때문에 transaction 걸어주시는 것이 좋겠습니다 :)

2023-10-23 09:11 UTC, soheon-lee commented on src/models/trainerMatchingDao.js
> +};
```suggestion
const updateTrainerMatchingStatus = async (productId, status) => {
  await AppDataSource.query(`
    UPDATE producsts
        status  = ${status}
        WHERE id = ${productsId};
    `);
};
```
1. 꼭 status가 삭제로 변경되는 상황이 아닌 경우에도 쓰일 수 있도록 확장성 있게 작성하셨네요 👍 그렇기 때문에 함수 이름도 delete 경우에만 국한되지 않도록 update로 사용하셔도 좋겠습니다.
2. status...가 그렇게 긴 변수명은 아니기 때문에, 원래 단어 그대로 써주셔도 좋을 것 같습니다 :)

2023-10-23 09:11 UTC, soheon-lee commented on src/models/trainerQueryBuilder.js
> +const products = async (offset, limit) => {
다른 쿼리 필터랑 달리 이 필터 이름은 products인가요?

2023-10-23 09:11 UTC, soheon-lee commented on src/routes/trainerMatchingRoute.js
> +  "/",
```suggestion
trainerMatchingRouter.get(
  "/products",
  asyncWrap(trainerMatchingController.getTrainerProduct)
);
trainerMatchingRouter.post(
  "/product",
```

1. [GET] "/trainer" 는 트레이너의 정보를 받아오는 API인 것 같은 의미를 띕니다.
2. 프론트와 통신상 조율이 가능하다면, uri 업데이트 하시는 것이 좋을 것 같습니다. (/trainer-proucts 혹은 /trainer/product 혹은 /training 을 추천드립니다)

2023-10-23 09:11 UTC, soheon-lee commented on src/models/trainerMatchingDao.js
> +const getTrainerMatchingDetail = async (userId, productsId) => {
이 함수는 트레이너의 운동 상품에 대한 상세 데이터를 조회하는 API인데, productId가 아닌 userId가 같이 필요한 이유가 따로 있을까요? productId만 있어도 될 것 같은데, 로직상 다른 고려 사항이 있다면 알려주세요

2023-10-23 09:11 UTC, soheon-lee commented on src/routes/trainerMatchingRoute.js
> +  asyncWrap(trainerMatchingController.getTrainerProductDetail)
```suggestion
trainerMatchingRouter.get(
  "/:trainerProductId,
  asyncWrap(trainerMatchingController.getTrainerProductDetail)
```

상세 정보를 조회할 것이라면, productId를 프론트로부터 받아오는 것이 일반적입니다. 로직상 불가능한 상황이라면 알려주세요.

2023-10-24 12:49 UTC, Wanderer94 commented on src/services/trainerMatchingService.js
> +    isAuth = false;
따로 나누어서 해결했습니다!

2023-10-24 12:53 UTC, Wanderer94 commented on src/models/trainerMatchingDao.js
> +};
아직 미구현이라 우선 id 찾는 것만 만들었습니다 이후에 필요 없다면 삭제 하겠습니다!

2023-10-24 13:08 UTC, Wanderer94 commented on src/models/trainerMatchingDao.js
> +const postTrainerMatching = async (
넵 감사합니다 확인할게요!

2023-10-24 13:11 UTC, Wanderer94 commented on src/routes/trainerMatchingRoute.js
> +  "/",
확인해서 training 으로 변경 했습니다!
/training 으로 해서 운동하는 것에 관련된 정보를 받아오는 걸로 보여지게 했어요!

2023-10-24 13:15 UTC, Wanderer94 commented on src/models/trainerQueryBuilder.js
> +const products = async (offset, limit) => {
쓸 말이 없어서... 수정하겠습니다!

2023-10-24 14:10 UTC, Wanderer94 commented on src/routes/trainerMatchingRoute.js
> +  asyncWrap(trainerMatchingController.getTrainerProductDetail)
위의 get 요청에서 쿼리로 sort 형식을 받아오기로 해서요 혹시 /detail/:trainerProductId이렇게 받아도 될까요?

2023-10-25 10:22 UTC, heyw00 approved these changes

2023-10-25 10:49 UTC, kimsw94 approved these changes

2023-10-25 10:51 UTC, heyw00 approved these changes

2023-10-25 11:47 UTC, soheon-lee approved these changes

2023-10-25 11:48 UTC, merged